export const EXERCISE_SEED = [
  // --- CHEST ---
  {
    id: 'bench_press',
    name: 'Barbell Bench Press',
    primary_muscle: 'Chest',
    equipment: 'Barbell',
    aliases: ['Bench Press', 'BB Bench', 'Chest Press'],
    image_url: 'https://img.icons8.com/ios/50/bench-press.png',
  },
  {
    id: 'incline_bench_press',
    name: 'Incline Barbell Bench Press',
    primary_muscle: 'Chest',
    equipment: 'Barbell',
    aliases: ['Incline Any', 'Incline BB Bench'],
    image_url: 'https://img.icons8.com/ios/50/bench-press.png', // Generic fallback
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    primary_muscle: 'Chest',
    equipment: 'Dumbbell',
    aliases: ['DB Bench', 'Dumbbell Press'],
    image_url: 'https://img.icons8.com/ios/50/chest-press.png',
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    primary_muscle: 'Chest',
    equipment: 'Dumbbell',
    aliases: ['Incline DB Press'],
    image_url: 'https://img.icons8.com/ios/50/chest-press.png', // Similar
  },
  {
    id: 'chest_fly',
    name: 'Dumbbell Chest Fly',
    primary_muscle: 'Chest',
    equipment: 'Dumbbell',
    aliases: ['Pec Fly', 'Chest Flys'],
    image_url: 'https://img.icons8.com/ios/50/stop-sign.png', // Placeholder for fly? Icons8 limited without search
  },
  {
    id: 'cable_crossover',
    name: 'Cable Crossover',
    primary_muscle: 'Chest',
    equipment: 'Cable',
    aliases: ['Cable Fly', 'Standing Fly'],
    image_url: 'https://img.icons8.com/ios/50/pullups.png', // Incorrect but visual
  },
  {
    id: 'push_up',
    name: 'Push Up',
    primary_muscle: 'Chest',
    equipment: 'Bodyweight',
    aliases: ['Pushup', 'Press Up'],
    image_url: 'https://img.icons8.com/ios/50/pushups.png',
  },
  {
    id: 'dips',
    name: 'Chest Dips',
    primary_muscle: 'Chest',
    equipment: 'Bodyweight',
    aliases: ['Dips', 'Parallel Bar Dips'],
    image_url: 'https://img.icons8.com/ios/50/pullups.png', // specific dip icon needed
  },
  {
    id: 'machine_chest_press',
    name: 'Machine Chest Press',
    primary_muscle: 'Chest',
    equipment: 'Machine',
    aliases: ['Seated Chest Press', 'Chest Machine'],
    image_url: 'https://img.icons8.com/ios/50/chest-press.png',
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck Machine',
    primary_muscle: 'Chest',
    equipment: 'Machine',
    aliases: ['Butterfly', 'Machine Fly'],
    image_url: 'https://img.icons8.com/ios/50/chest-press.png',
  },
  {
    id: 'smith_bench_press',
    name: 'Smith Machine Bench Press',
    primary_muscle: 'Chest',
    equipment: 'Machine',
    aliases: ['Smith Bench'],
    image_url: 'https://img.icons8.com/ios/50/bench-press.png',
  },
  {
    id: 'decline_bench_press',
    name: 'Decline Bench Press',
    primary_muscle: 'Chest',
    equipment: 'Barbell',
    aliases: ['Decline Press'],
    image_url: 'https://img.icons8.com/ios/50/bench-press.png',
  },
  {
    id: 'floor_press',
    name: 'Floor Press',
    primary_muscle: 'Chest',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/bench-press.png',
  },
  {
    id: 'svend_press',
    name: 'Svend Press',
    primary_muscle: 'Chest',
    equipment: 'Plate',
    aliases: ['Plate Press'],
    image_url: 'https://img.icons8.com/ios/50/weight-plate.png',
  },
  {
    id: 'pullover',
    name: 'Dumbbell Pullover',
    primary_muscle: 'Chest',
    equipment: 'Dumbbell',
    aliases: ['Chest Pullover'],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'landmine_press',
    name: 'Landmine Press',
    primary_muscle: 'Chest',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/barbell.png',
  },
  {
    id: 'wide_push_up',
    name: 'Wide Grip Push Up',
    primary_muscle: 'Chest',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/pushups.png',
  },
  {
    id: 'diamond_push_up',
    name: 'Diamond Push Up',
    primary_muscle: 'Chest',
    equipment: 'Bodyweight',
    aliases: ['Triangle Push Up'],
    image_url: 'https://img.icons8.com/ios/50/pushups.png',
  },
  {
    id: 'chest_press_machine',
    name: 'Hammer Strength Chest Press',
    primary_muscle: 'Chest',
    equipment: 'Machine',
    aliases: ['Hammer Press'],
    image_url: 'https://img.icons8.com/ios/50/chest-press.png',
  },
  {
    id: 'single_arm_db_press',
    name: 'Single Arm Dumbbell Press',
    primary_muscle: 'Chest',
    equipment: 'Dumbbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },

  // --- BACK ---
  {
    id: 'deadlift',
    name: 'Deadlift',
    primary_muscle: 'Back',
    equipment: 'Barbell',
    aliases: ['Conventional Deadlift', 'DL'],
    image_url: 'https://img.icons8.com/ios/50/deadlift.png',
  },
  {
    id: 'pull_up',
    name: 'Pull Up',
    primary_muscle: 'Back',
    equipment: 'Bodyweight',
    aliases: ['Chin Up', 'Pullups'],
    image_url: 'https://img.icons8.com/ios/50/pullups.png',
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    primary_muscle: 'Back',
    equipment: 'Machine',
    aliases: ['Pulldowns'],
    image_url: 'https://img.icons8.com/ios/50/lat-pulldown.png', // guess
  },
  {
    id: 'bent_over_row',
    name: 'Barbell Row',
    primary_muscle: 'Back',
    equipment: 'Barbell',
    aliases: ['Bent Over Row', 'BB Row'],
    image_url: 'https://img.icons8.com/ios/50/rowing.png',
  },
  {
    id: 'dumbbell_row',
    name: 'Single Arm Dumbbell Row',
    primary_muscle: 'Back',
    equipment: 'Dumbbell',
    aliases: ['DB Row', 'Kroc Row'],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    primary_muscle: 'Back',
    equipment: 'Cable',
    aliases: ['Cable Row'],
    image_url: 'https://img.icons8.com/ios/50/rowing-machine.png',
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    primary_muscle: 'Back',
    equipment: 'Cable',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 't_bar_row',
    name: 'T-Bar Row',
    primary_muscle: 'Back',
    equipment: 'Machine',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/rowing.png',
  },
  {
    id: 'chest_supported_row',
    name: 'Chest Supported Row',
    primary_muscle: 'Back',
    equipment: 'Machine',
    aliases: ['Machine Row'],
    image_url: 'https://img.icons8.com/ios/50/rowing.png',
  },
  {
    id: 'straight_arm_pulldown',
    name: 'Straight Arm Pulldown',
    primary_muscle: 'Back',
    equipment: 'Cable',
    aliases: ['Cable Pullover'],
    image_url: 'https://img.icons8.com/ios/50/cable-release.png',
  },
  {
    id: 'rack_pull',
    name: 'Rack Pull',
    primary_muscle: 'Back',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/deadlift.png',
  },
  {
    id: 'shrugs',
    name: 'Barbell Shrug',
    primary_muscle: 'Back',
    equipment: 'Barbell',
    aliases: ['Traps'],
    image_url: 'https://img.icons8.com/ios/50/shoulders.png',
  },
  {
    id: 'dumbbell_shrug',
    name: 'Dumbbell Shrug',
    primary_muscle: 'Back',
    equipment: 'Dumbbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'hyperextension',
    name: 'Back Hyperextension',
    primary_muscle: 'Back',
    equipment: 'Bodyweight',
    aliases: ['Back Extension'],
    image_url: 'https://img.icons8.com/ios/50/back-muscles.png',
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    primary_muscle: 'Back',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/back-muscles.png',
  },
  {
    id: 'pendlay_row',
    name: 'Pendlay Row',
    primary_muscle: 'Back',
    equipment: 'Barbell',
    aliases: ['Strict Row'],
    image_url: 'https://img.icons8.com/ios/50/rowing.png',
  },
  {
    id: 'meadows_row',
    name: 'Meadows Row',
    primary_muscle: 'Back',
    equipment: 'Barbell',
    aliases: ['Landmine Row'],
    image_url: 'https://img.icons8.com/ios/50/rowing.png',
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    primary_muscle: 'Back',
    equipment: 'Bodyweight',
    aliases: ['Australian Pullup'],
    image_url: 'https://img.icons8.com/ios/50/pullups.png',
  },
  {
    id: 'renegade_row',
    name: 'Renegade Row',
    primary_muscle: 'Back',
    equipment: 'Dumbbell',
    aliases: ['Plank Row'],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'muscle_up',
    name: 'Muscle Up',
    primary_muscle: 'Back',
    equipment: 'Bodyweight',
    aliases: ['Bar Muscle Up'],
    image_url: 'https://img.icons8.com/ios/50/pullups.png',
  },

  // --- LEGS ---
  {
    id: 'squat',
    name: 'Barbell Squat',
    primary_muscle: 'Legs',
    equipment: 'Barbell',
    aliases: ['Back Squat', 'Squats'],
    image_url: 'https://img.icons8.com/ios/50/squats.png',
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    primary_muscle: 'Legs',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/squats.png',
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/leg-press.png', // guess
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: ['Quad Extension'],
    image_url: 'https://img.icons8.com/ios/50/leg.png',
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: ['Hamstring Curl', 'Seated Leg Curl'],
    image_url: 'https://img.icons8.com/ios/50/leg.png',
  },
  {
    id: 'lying_leg_curl',
    name: 'Lying Leg Curl',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/leg.png',
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    primary_muscle: 'Legs',
    equipment: 'Dumbbell',
    aliases: ['Lunges'],
    image_url: 'https://img.icons8.com/ios/50/lunge.png', // guess
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    primary_muscle: 'Legs',
    equipment: 'Dumbbell',
    aliases: ['BSS', 'Split Squat'],
    image_url: 'https://img.icons8.com/ios/50/lunge.png',
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    primary_muscle: 'Legs',
    equipment: 'Barbell',
    aliases: ['RDL', 'Stiff Leg Deadlift'],
    image_url: 'https://img.icons8.com/ios/50/deadlift.png',
  },
  {
    id: 'dumbbell_rdl',
    name: 'Dumbbell RDL',
    primary_muscle: 'Legs',
    equipment: 'Dumbbell',
    aliases: ['DB RDL'],
    image_url: 'https://img.icons8.com/ios/50/deadlift.png',
  },
  {
    id: 'calf_raise',
    name: 'Standing Calf Raise',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: ['Calves'],
    image_url: 'https://img.icons8.com/ios/50/calves.png',
  },
  {
    id: 'seated_calf_raise',
    name: 'Seated Calf Raise',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/calves.png',
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/squats.png',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    primary_muscle: 'Legs',
    equipment: 'Dumbbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/squats.png',
  },
  {
    id: 'hip_thrust',
    name: 'Barbell Hip Thrust',
    primary_muscle: 'Legs',
    equipment: 'Barbell',
    aliases: ['Glute Bridge'],
    image_url: 'https://img.icons8.com/ios/50/pelvis.png',
  },
  {
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    primary_muscle: 'Legs',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/deadlift.png',
  },
  {
    id: 'glute_kickback',
    name: 'Cable Glute Kickback',
    primary_muscle: 'Legs',
    equipment: 'Cable',
    aliases: ['Kickbacks'],
    image_url: 'https://img.icons8.com/ios/50/leg.png',
  },
  {
    id: 'step_up',
    name: 'Step Up',
    primary_muscle: 'Legs',
    equipment: 'Dumbbell',
    aliases: ['Box Step Up'],
    image_url: 'https://img.icons8.com/ios/50/stairs.png',
  },
  {
    id: 'adductor_machine',
    name: 'Hip Adduction',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: ['Adductor', 'Good Girl'],
    image_url: 'https://img.icons8.com/ios/50/leg.png',
  },
  {
    id: 'abductor_machine',
    name: 'Hip Abduction',
    primary_muscle: 'Legs',
    equipment: 'Machine',
    aliases: ['Abductor', 'Bad Girl'],
    image_url: 'https://img.icons8.com/ios/50/leg.png',
  },

  // --- SHOULDERS ---
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    primary_muscle: 'Shoulders',
    equipment: 'Barbell',
    aliases: ['OHP', 'Military Press', 'Shoulder Press'],
    image_url: 'https://img.icons8.com/ios/50/shoulders.png',
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    primary_muscle: 'Shoulders',
    equipment: 'Dumbbell',
    aliases: ['Seated DB Press'],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'lateral_raise',
    name: 'Dumbbell Lateral Raise',
    primary_muscle: 'Shoulders',
    equipment: 'Dumbbell',
    aliases: ['Side Raise', 'Lat Raise'],
    image_url: 'https://img.icons8.com/ios/50/shoulders.png',
  },
  {
    id: 'front_raise',
    name: 'Dumbbell Front Raise',
    primary_muscle: 'Shoulders',
    equipment: 'Dumbbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/shoulders.png',
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    primary_muscle: 'Shoulders',
    equipment: 'Cable',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/shoulders.png',
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    primary_muscle: 'Shoulders',
    equipment: 'Dumbbell',
    aliases: ['Bent Over Fly'],
    image_url: 'https://img.icons8.com/ios/50/shoulders.png',
  },
  {
    id: 'reverse_pec_deck',
    name: 'Reverse Pec Deck',
    primary_muscle: 'Shoulders',
    equipment: 'Machine',
    aliases: ['Rear Delt Machine'],
    image_url: 'https://img.icons8.com/ios/50/chest-press.png',
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    primary_muscle: 'Shoulders',
    equipment: 'Dumbbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'upright_row',
    name: 'Barbell Upright Row',
    primary_muscle: 'Shoulders',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/barbell.png',
  },
  {
    id: 'egyptian_lateral_raise',
    name: 'Egyptian Lateral Raise',
    primary_muscle: 'Shoulders',
    equipment: 'Cable',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/shoulders.png',
  },
  {
    id: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    primary_muscle: 'Shoulders',
    equipment: 'Machine',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/shoulders.png',
  },
  {
    id: 'landmine_press_shoulder', // ID conflict with chest? No. 
    name: 'Single Arm Landmine Press',
    primary_muscle: 'Shoulders',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/barbell.png',
  },
  {
    id: 'push_press',
    name: 'Push Press',
    primary_muscle: 'Shoulders',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/barbell.png',
  },
  {
    id: 'behind_neck_press',
    name: 'Behind The Neck Press',
    primary_muscle: 'Shoulders',
    equipment: 'Barbell',
    aliases: ['BTN Press'],
    image_url: 'https://img.icons8.com/ios/50/barbell.png',
  },
  {
    id: 'lu_raise',
    name: 'Lu Raise',
    primary_muscle: 'Shoulders',
    equipment: 'Plate',
    aliases: ['Chinese Lateral Raise'],
    image_url: 'https://img.icons8.com/ios/50/weight-plate.png',
  },

  // --- ARMS ---
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    primary_muscle: 'Biceps',
    equipment: 'Barbell',
    aliases: ['Bicep Curl'],
    image_url: 'https://img.icons8.com/ios/50/biceps.png',
  },
  {
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    primary_muscle: 'Biceps',
    equipment: 'Dumbbell',
    aliases: ['Standing Curl'],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    primary_muscle: 'Biceps',
    equipment: 'Dumbbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    primary_muscle: 'Biceps',
    equipment: 'Barbell',
    aliases: ['EZ Bar Preacher'],
    image_url: 'https://img.icons8.com/ios/50/biceps.png',
  },
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    primary_muscle: 'Triceps',
    equipment: 'Cable',
    aliases: ['Cable Pushdown'],
    image_url: 'https://img.icons8.com/ios/50/triceps.png',
  },
  {
    id: 'skullcrusher',
    name: 'Skullcrusher',
    primary_muscle: 'Triceps',
    equipment: 'Barbell',
    aliases: ['Lying Tricep Extension'],
    image_url: 'https://img.icons8.com/ios/50/triceps.png',
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    primary_muscle: 'Triceps',
    equipment: 'Dumbbell',
    aliases: ['French Press'],
    image_url: 'https://img.icons8.com/ios/50/triceps.png',
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    primary_muscle: 'Biceps',
    equipment: 'Cable',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/biceps.png',
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    primary_muscle: 'Biceps',
    equipment: 'Dumbbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'spider_curl',
    name: 'Spider Curl',
    primary_muscle: 'Biceps',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/biceps.png',
  },
  {
    id: 'incline_curl',
    name: 'Incline Dumbbell Curl',
    primary_muscle: 'Biceps',
    equipment: 'Dumbbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'bayesian_curl',
    name: 'Bayesian Curl',
    primary_muscle: 'Biceps',
    equipment: 'Cable',
    aliases: ['Behind Body Cable Curl'],
    image_url: 'https://img.icons8.com/ios/50/biceps.png',
  },
  {
    id: 'reverse_curl',
    name: 'Reverse Curl',
    primary_muscle: 'Forearms',
    equipment: 'Barbell',
    aliases: ['Forearm Curl'],
    image_url: 'https://img.icons8.com/ios/50/biceps.png',
  },
  {
    id: 'wrist_curl',
    name: 'Wrist Curl',
    primary_muscle: 'Forearms',
    equipment: 'Dumbbell',
    aliases: ['Forearms'],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
  {
    id: 'close_grip_bench',
    name: 'Close Grip Bench Press',
    primary_muscle: 'Triceps',
    equipment: 'Barbell',
    aliases: ['CGBP'],
    image_url: 'https://img.icons8.com/ios/50/triceps.png',
  },
  {
    id: 'diamond_pushup_arms',
    name: 'Diamond Pushup (Triceps)',
    primary_muscle: 'Triceps',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/pushups.png',
  },
  {
    id: 'bench_dip',
    name: 'Bench Dip',
    primary_muscle: 'Triceps',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/triceps.png',
  },
  {
    id: 'rope_pushdown',
    name: 'Rope Pushdown',
    primary_muscle: 'Triceps',
    equipment: 'Cable',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/triceps.png',
  },
  {
    id: 'single_arm_pushdown',
    name: 'Single Arm Pushdown',
    primary_muscle: 'Triceps',
    equipment: 'Cable',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/triceps.png',
  },
  {
    id: 'ez_bar_curl',
    name: 'EZ Bar Curl',
    primary_muscle: 'Biceps',
    equipment: 'Barbell',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/biceps.png',
  },

  // --- CORE/ABS ---
  {
    id: 'plank',
    name: 'Plank',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: ['Front Plank'],
    image_url: 'https://img.icons8.com/ios/50/plank.png',
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: ['Toes to Bar'],
    image_url: 'https://img.icons8.com/ios/50/pullups.png',
  },
  {
    id: 'crunch',
    name: 'Crunch',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: ['Sit Up'],
    image_url: 'https://img.icons8.com/ios/50/sit-ups.png',
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    primary_muscle: 'Core',
    equipment: 'Cable',
    aliases: ['Kneeling Cable Crunch'],
    image_url: 'https://img.icons8.com/ios/50/sit-ups.png',
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/sit-ups.png',
  },
  {
    id: 'ab_wheel',
    name: 'Ab Wheel Rollout',
    primary_muscle: 'Core',
    equipment: 'Other',
    aliases: ['Ab Roller'],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 'mountain_climber',
    name: 'Mountain Climber',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/sit-ups.png',
  },
  {
    id: 'leg_raise',
    name: 'Lying Leg Raise',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/sit-ups.png',
  },
  {
    id: 'woodchopper',
    name: 'Cable Woodchopper',
    primary_muscle: 'Core',
    equipment: 'Cable',
    aliases: ['Wood Chop'],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 'side_plank',
    name: 'Side Plank',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/plank.png',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 'dragon_flag',
    name: 'Dragon Flag',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 'v_up',
    name: 'V-Up',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: ['Jackknife'],
    image_url: 'https://img.icons8.com/ios/50/sit-ups.png',
  },
  {
    id: 'hollow_hold',
    name: 'Hollow Body Hold',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 'flutter_kicks',
    name: 'Flutter Kicks',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/leg.png',
  },
  {
    id: 'pallof_press',
    name: 'Pallof Press',
    primary_muscle: 'Core',
    equipment: 'Cable',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 'reverse_crunch',
    name: 'Reverse Crunch',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/sit-ups.png',
  },
  {
    id: 'l_sit',
    name: 'L-Sit',
    primary_muscle: 'Core',
    equipment: 'Bodyweight',
    aliases: [],
    image_url: 'https://img.icons8.com/ios/50/workout.png',
  },
  {
    id: 'farmers_walk',
    name: 'Farmers Walk',
    primary_muscle: 'Core',
    equipment: 'Dumbbell',
    aliases: ['Carry'],
    image_url: 'https://img.icons8.com/ios/50/dumbbell.png',
  },
];
